name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - php-version: 8.0.8
            tag-major: true
          - php-version: 7.4.21
            tag-major: true
          - php-version: 5.4.45
            system-packages: zlib1g-dev
            pecl-extensions: -uuid -redis -xdebug uuid-1.0.5 redis-4.3.0 xdebug-2.4.1 zendopcache
            php-extensions-install: mbstring mysql
    name: Build ${{ matrix.variant.php-version }}
    steps:
      -
        id: php-version
        name: Generate major/minor/patch variables (${{ matrix.variant.php-version }})
        env:
          IMAGE_NAME: php
        run: |
          echo "::set-output name=major::$(echo ${{ matrix.variant.php-version }} | cut -d'.' -f1)"
          echo "::set-output name=minor::$(echo ${{ matrix.variant.php-version }} | cut -d'.' -f2)"
          echo "::set-output name=patch::$(echo ${{ matrix.variant.php-version }} | cut -d'.' -f3)"
      -
        name: Checkout source
        uses: actions/checkout@v2
      -
        name: Docker meta (major)
        id: meta-major
        uses: docker/metadata-action@v3
        if: ${{ matrix.variant.tag-major }}
        with:
          images: jameswestnz/php
          flavor: |
            latest=false
          tags: |
            type=semver,prefix=${{ steps.php-version.outputs.major }}-apache-,pattern={{version}}
            type=semver,prefix=${{ steps.php-version.outputs.major }}-apache-,pattern={{major}}.{{minor}}
            type=semver,prefix=${{ steps.php-version.outputs.major }}-apache-,pattern={{major}}
      -
        name: Docker meta (minor)
        id: meta-minor
        uses: docker/metadata-action@v3
        with:
          images: jameswestnz/php
          flavor: |
            latest=false
          tags: |
            type=semver,prefix=${{ steps.php-version.outputs.major }}.${{ steps.php-version.outputs.minor }}-apache-,pattern={{version}}
            type=semver,prefix=${{ steps.php-version.outputs.major }}.${{ steps.php-version.outputs.minor }}-apache-,pattern={{major}}.{{minor}}
            type=semver,prefix=${{ steps.php-version.outputs.major }}.${{ steps.php-version.outputs.minor }}-apache-,pattern={{major}}
      -
        name: Docker meta (patch)
        id: meta-patch
        uses: docker/metadata-action@v3
        with:
          images: jameswestnz/php
          flavor: |
            latest=false
          tags: |
            type=semver,prefix=${{ steps.php-version.outputs.major }}.${{ steps.php-version.outputs.minor }}.${{ steps.php-version.outputs.patch }}-apache-,pattern={{version}}
            type=semver,prefix=${{ steps.php-version.outputs.major }}.${{ steps.php-version.outputs.minor }}.${{ steps.php-version.outputs.patch }}-apache-,pattern={{major}}.{{minor}}
            type=semver,prefix=${{ steps.php-version.outputs.major }}.${{ steps.php-version.outputs.minor }}.${{ steps.php-version.outputs.patch }}-apache-,pattern={{major}}
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.variant.php-version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.variant.php-version }}-
      -
        name: Build and push (${{ matrix.variant.php-version }})
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          tags: |
            ${{ steps.meta-major.outputs.tags }}
            ${{ steps.meta-minor.outputs.tags }}
            ${{ steps.meta-patch.outputs.tags }}
          labels: ${{ steps.meta-patch.outputs.labels }}
          build-args: |
            PHP_VERSION=${{ matrix.variant.php-version }}
            SYSTEM_PACKAGES="${{ matrix.variant.system-packages }}"
            PECL_EXTENSIONS="${{ matrix.variant.pecl-extensions }}"
            PHP_EXTENSIONS_INSTALL="${{ matrix.variant.php-extensions-install }}"
            PHP_EXTENSIONS_ENABLE="${{ matrix.variant.php-extensions-enable }}"
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
